MDBoxLayout:
    orientation:'vertical'


    #MDScreen:
    MDLabel:
        id:my_label
        text:'some stuff'
        halign:'center'

    MDFloatingActionButtonSpeedDial:
        id:speed_dial
        data:app.datta
        root_button_anim:True
        label_text_color:1,0,0,1
        bg_color_root_button:0.25,1,1,1
        color_icon_stack_button:0,0,1,1
        hint_animation:True







